workoutscheduler_project-master/todolist/urls.py
from django.conf.urls import url
from todolist.views import *

urlpatterns = [
    # Example: /
    url(r'^$', WorkoutTAV.as_view(), name='default_workout_list'),

    # Example: /today
    url(r'^today/$', WorkoutTAV.as_view(), name='today_workout_list'),

    url(r'^today_issue/$', today_issue, name='today_issue'),

    url(r'^today_best/$', today_best, name='today_best'),

    url(r'^today_frined/$', today_friend, name='today_frined'),

    # Example: /2017/may/25
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', WorkoutDAV.as_view(), name='workout_day_archive'),

    # Example: /workout/update/1
    url(r'^workout/update/$', workout_update, name='workout_update'),

    url(r'^workout/new', workout_new, name='workout_new'),
]

workoutscheduler_project-master/workoutcalendar/urls.py
from django.conf.urls import url
from workoutcalendar.views import *

urlpatterns = [
    # Example: /
    url(r'^$', WorkoutCalendarTV.as_view(), name='workout_calendar'),
    url(r'popcontent/(?P<id>.*)/$', pop, name='popup'),

    # Example: /2017/5/
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', WorkoutCalendarTV.as_view(), name='workout_month_calendar'),
]

workoutscheduler_project-master/workoutscheduler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from workoutscheduler.views import HomeView
from workoutscheduler.views import UserCreateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Authentication
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'accounts/register/$', UserCreateView.as_view(), name='register'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^todolist/', include('todolist.urls', namespace='todolist')),
    url(r'^calendar/', include('workoutcalendar.urls', namespace='calendar')),
    url(r'^stats/', include('workoutstats.urls', namespace='stats')),
]

workoutscheduler_project-master/todolist/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User




@python_2_unicode_compatible
class Workout(models.Model):
    workout = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    # record modified time for object
    # This will be used to figure out when this workout performed (by checking workout_done flag)
    workout_date = models.DateTimeField('Workout Date', default=datetime.today())
    duration = models.IntegerField('Duration', default=0)

    owner = models.ForeignKey(User, null=False)
    workout_done = models.BooleanField(default=False)  # flag to check whether workout done or not

    def __str__(self):
        return str(self.workout)



class Calink(models.Model):
    owner = models.ForeignKey(User, null=False)
    link = models.CharField(max_length= 100)
    create_date = models.DateTimeField(default=datetime.today())


class Cafriend(models.Model):
    owner = models.ForeignKey(User, null=False)
    fname = models.CharField(max_length = 50)
    count = models.CharField(max_length = 50)

workoutscheduler_project-master/todolist/views.py
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from todolist.models import Workout
from . import best_friend
from django.shortcuts import render
from .models import Cafriend, Calink
from . import si, best_friend

class WorkoutTAV(TodayArchiveView):
    model = Workout
    date_field = 'workout_date'
    allow_empty = True  # Display the page if no objects are available

    # only lists own by logged in user
    def get_queryset(self):
        return Workout.objects.filter(owner_id=self.request.user.id)


class WorkoutDAV(DayArchiveView):
    model = Workout
    date_field = 'workout_date'
    allow_empty = True

    def get_queryset(self):
        return Workout.objects.filter(owner_id=self.request.user.id)


def workout_update(request):
    title = request.POST.get('workout')

    content = request.POST.get('content')
    name  = User.objects.get(username = request.user.get_username())
    workout = Workout(
        workout = title,
        content = content,
        owner = name)
    workout.save()
    return HttpResponseRedirect(reverse('todolist:today_workout_list'))


def workout_new(request):
    title = request.POST.get('workout')

    content = request.POST.get('content')
    name = User.objects.get(username=request.user.get_username())
    workout = Workout(
        workout=title,
        content=content,
        owner=name)
    workout.save()
    return HttpResponseRedirect(reverse('todolist:today_workout_list'))

def today_best(request):

    return render(request, 'todolist/today_best.html')
def today_friend(request):
    #friend = []
    #friend = best_friend.riri()

    #for f1, f2 in friend:
    #    cafriend = Cafriend(
    #        owner = User.objects.get(username=request.user.get_username()),
    #        fname = f1,
    #       count = f2)

    #    cafriend.save()
    final = Cafriend.objects.order_by('pk').last()
    cafriends = Cafriend.objects.exclude(pk = final.pk)
 
    return render(request, 'todolist/today_friend.html', {'cafriends':cafriends})
def today_issue(request):
    #aa = []
    #a = si.riri('openhack2.csv')
    #for i in a:
    #   aa.append(i)


    #name  = User.objects.get(username = request.user.get_username())

    #for a in aa:
    #    calink = Calink(
    #        owner = name,
    #        link = a
    #        )
    #    calink.save()

    calinks = Calink.objects.filter()
    
    return render(request, 'todolist/today.html', {'calinks': calinks})

workoutscheduler_project-master/todolist/templates/todolist/today.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="color:#995a07;font-size:1em;font-weight: bold;">
    <div class="row" style="color"><hr/></div>
    <div class="row">
        <div class="col s2 offset-s2"><a href="{% url 'todolist:today_frined' %}">TODAY</a></div>
        <div class="col s2"><a style = "font-size: 18px" href="{% url 'todolist:today_issue' %}">URL 모음</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_best' %}"><span style="font-color:#995a07;">베스트샷</span></a></div>
        <div class="col s2"><a href="{% url 'todolist:today_workout_list' %}">일기쓰기</a></div>
        <div class="col s2"><a href="{% url 'calendar:workout_calendar' %}">이전기록</a></div>
    </div>
    <div class="row"><hr/></div>
</div>


<main>

<div class="container">

<div>
    <h4 class="grey-text center">{{ day|date:"Y년 N j일, D"}}</h4>


    <div class="row">
        <div class="col l8 offset-l2 s12">
          <ul>
          {% for calink in calinks %}
            <li><a href = "{{calink.link}}">{{calink.link}}</a></li>
            
          {% endfor %}
        </ul>
        </div>
    </div>


</div>

{% endblock %}

workoutscheduler_project-master/todolist/templates/todolist/today_best.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="color:#995a07;font-size:1em;font-weight: bold;">
    <div class="row" style="color"><hr/></div>
    <div class="row">
        <div class="col s2 offset-s2"><a style = "font-size: 18px" href="{% url 'todolist:today_frined' %}">TODAY</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_issue' %}">URL 모음</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_best' %}"><span style="font-color:#995a07;"><strong>베스트샷</strong></span></a></div>
        <div class="col s2"><a href="{% url 'todolist:today_workout_list' %}">일기쓰기</a></div>
        <div class="col s2"><a href="{% url 'calendar:workout_calendar' %}">이전기록</a></div>
    </div>
    <div class="row"><hr/></div>
</div>


<main>

<div class="container">

<div>
    <h4 class="grey-text center">{{ day|date:"Y년 N j일, D"}}</h4>


    <div class="row">
        <div class="col l8 offset-l2 s12">
<h1>서비스 중비 중 ......</h1>
        </div>
    </div>


</div>

{% endblock %}

workoutscheduler_project-master/todolist/templates/todolist/today_friend.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="color:#995a07;font-size:1em;font-weight: bold;">
    <div class="row" style="color"><hr/></div>
    <div class="row">
        <div class="col s2 offset-s2"><a style = "font-size: 18px" href="{% url 'todolist:today_frined' %}">TODAY</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_issue' %}">URL 모음</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_best' %}"><span style="font-color:#995a07;">베스트샷</span></a></div>
        <div class="col s2"><a href="{% url 'todolist:today_workout_list' %}">일기쓰기</a></div>
        <div class="col s2"><a href="{% url 'calendar:workout_calendar' %}">이전기록</a></div>
    </div>
    <div class="row"><hr/></div>
</div>


<main>

<div class="container">

<div>
    <h4 class="grey-text center">{{ day|date:"Y년 N j일, D"}}</h4>


    <div class="row">
        <div class="col l8 offset-l2 s12">

          <ul>
          {% for cafriend in cafriends %}
            <li>{{cafriend.fname}}:  {{cafriend.count}}</li>
            
          {% endfor %}
        </ul>
        </div>
    </div>


</div>

{% endblock %}

workoutscheduler_project-master/todolist/templates/todolist/workout_archive_day.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="color:#995a07;font-size:1em;font-weight: bold;">
    <div class="row" style="color"><hr/></div>
    <div class="row">
        <div class="col s2 offset-s2"><a href="{% url 'todolist:today_frined' %}">TODAY</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_issue' %}">URL 모음</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_best' %}"><span style="font-color:#995a07;">베스트샷</span></a></div>
        <div class="col s2"><a style = "font-size: 18px" href="{% url 'todolist:today_workout_list' %}">일기쓰기</a></div>
        <div class="col s2"><a href="{% url 'calendar:workout_calendar' %}">이전기록</a></div>
    </div>
    <div class="row"><hr/></div>
</div>


<main>

<div class="container">
<div>
    <h4 class="center">{{ day|date:"Y년 N j일, D"}}</h4>


    <div class="row">
        <div class="col l8 offset-l2 s12">
           <form action="{% url 'todolist:workout_new'%}" method="post" id="myForm">
            {%csrf_token%}
                <input type="text" name="workout" style="font-size:30pt;">
                <div style="background-image: url('/static/img/note.png'); padding-left: 120px;padding-top: 110px;">
                    <textarea name="content" cols="50" style="font-size:30pt;height:20em;width:600px;border: none"></textarea>
                </div>
            </form>
        </div>
    </div>


</div>
<div class="fixed-action-btn">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">mode_edit</i>
  </a>
  <ul>
    <li><a class="btn-floating yellow darken-1" onclick="set_sunny();"><i class="material-icons">wb_sunny</i></a></li>
    <li><a class="btn-floating blue darken-3" onclick="set_rainny();"><i class="material-icons">invert_colors</i></a></li>
    <li><a class="btn-floating green"><i class="material-icons">autorenew</i></a></li>
    <li><a class="btn-floating blue" onclick="submit()"><i class="material-icons">save</i></a></li>
  </ul>
</div>


<script>

    function set_sunny() {
        alert("기분이 좋으시군요~")
    }

    function set_rainny() {
        alert("기분이 안좋으신가요? 힘내세요~")
    }

    function submit() {
        document.getElementById("myForm").submit();
    }

    document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, {
      hoverEnabled: false
    });
  });

  // Or with jQuery

</script>
{% endblock %}