workoutscheduler_project-master/todolist/urls.py
from django.conf.urls import url
from todolist.views import *

urlpatterns = [
    # Example: /
    url(r'^$', WorkoutTAV.as_view(), name='default_workout_list'),

    # Example: /today
    url(r'^today/$', WorkoutTAV.as_view(), name='today_workout_list'),

    url(r'^today_issue/$', today_issue, name='today_issue'),

    url(r'^today_best/$', today_best, name='today_best'),

    url(r'^today_frined/$', today_friend, name='today_frined'),

    # Example: /2017/may/25
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', WorkoutDAV.as_view(), name='workout_day_archive'),

    # Example: /workout/update/1
    url(r'^workout/update/$', workout_update, name='workout_update'),

    url(r'^workout/new', workout_new, name='workout_new'),
]

workoutscheduler_project-master/workoutcalendar/urls.py
from django.conf.urls import url
from workoutcalendar.views import *

urlpatterns = [
    # Example: /
    url(r'^$', WorkoutCalendarTV.as_view(), name='workout_calendar'),
    url(r'popcontent/(?P<id>.*)/$', pop, name='popup'),

    # Example: /2017/5/
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', WorkoutCalendarTV.as_view(), name='workout_month_calendar'),
]

workoutscheduler_project-master/workoutscheduler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from workoutscheduler.views import HomeView
from workoutscheduler.views import UserCreateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Authentication
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'accounts/register/$', UserCreateView.as_view(), name='register'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^todolist/', include('todolist.urls', namespace='todolist')),
    url(r'^calendar/', include('workoutcalendar.urls', namespace='calendar')),
    url(r'^stats/', include('workoutstats.urls', namespace='stats')),
]

workoutscheduler_project-master/workoutcalendar/models.py
from django.db import models

# Create your models here.

workoutscheduler_project-master/workoutcalendar/views.py
from datetime import date, datetime
from calendar import HTMLCalendar, month_name
from itertools import groupby
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils.safestring import mark_safe
from django.utils.html import conditional_escape as esc
from django.urls import reverse
from todolist.models import Workout, Calink

def pop(request, id):
    workout = Workout.objects.get(pk=id)

    return render(request, 'child.html', {'workout': workout})

class WorkoutCalendarTV(TemplateView):
    template_name = 'calendar.html'

    def get_context_data(self, **kwargs):
        context = super(WorkoutCalendarTV, self).get_context_data(**kwargs)
        year = datetime.now().year
        month = datetime.now().month

        if 'year' in self.kwargs and 'month' in self.kwargs:
            year = int(self.kwargs['year'])
            month = int(self.kwargs['month'])

        my_workouts = Workout.objects.order_by('create_date').filter(
            workout_date__year=year, workout_date__month=month, owner_id=self.request.user.id
        )
        cal = WorkoutCalendar(my_workouts).formatmonth(year, month)
        context['calendar'] = mark_safe(cal)
        return context


class WorkoutCalendar(HTMLCalendar):

    def __init__(self, workouts):
        super(WorkoutCalendar, self).__init__(firstweekday=6)  # start from sunday (pass argument to super function)
        self.workouts = self.group_by_day(workouts)

    def formatday(self, day, weekday):
        if day != 0:
            cssclass = self.cssclasses[weekday]
            if date.today() == date(self.year, self.month, day):
                cssclass += ' today orange lighten-3'
            if day in self.workouts:
                cssclass += ' filled'
                body = ['<ul>']
                for workout in self.workouts[day]:
                    body.append('<li><h6>')
                    body.append('<a href = /calendar/popcontent/' + str(workout.id) + '>' + esc(workout.workout) + '</a>')
                    body.append("<div style = 'display: none;''>"+"<input type = 'text' name = 'content'>" + esc(workout.content) + "</input>"+"</div>")
                    body.append('</li></h6>')
                body.append('</ul>')
                return self.day_cell(cssclass, '%d %s' % (day, ''.join(body)))
            return self.day_cell(cssclass, day)
        return self.day_cell('noday', '&nbsp;')

    def formatmonthname(self, year, month, withyear=True):
        if withyear:
            s = '%s %s' % (month_name[month], year)
        else:
            s = '%s' % month_name[month]
        return '<tr><th colspan="1" class="month_arrow">' \
               '<a href="%s"><i class="fa fa-arrow-left" aria-hidden="true"></i></a></th>' \
               '<th colspan="5" class="month">%s</th>' \
               '<th colspan="1" class="month_arrow">' \
               '<a href="%s"><i class="fa fa-arrow-right" aria-hidden="true"></i><a/></th></tr>' \
               % (reverse('calendar:workout_month_calendar', kwargs=self.get_previous_month(year, month)), s,
                  reverse('calendar:workout_month_calendar', kwargs=self.get_next_month(year, month)))

    # return one-month calendar
    def formatmonth(self, year, month):
        self.year, self.month = year, month
        return super(WorkoutCalendar, self).formatmonth(year, month)

    @classmethod
    def group_by_day(cls, workouts):
        field = lambda workout: workout.workout_date.day
        return dict(
            [(day, list(items)) for day, items in groupby(workouts, field)]
        )

    @classmethod
    def day_cell(cls, cssclasses, body):
        return '<td class="%s">%s</td>' % (cssclasses, body)

    @classmethod
    def get_previous_month(cls, year, month):
        if month == 1:
            return {"year": year-1, "month": 12}
        else:
            return {"year": year, "month": month-1}

    @classmethod
    def get_next_month(cls, year, month):
        if month == 12:
            return {"year": year + 1, "month": 1}
        else:
            return {"year": year, "month": month + 1}

workoutscheduler_project-master/workoutcalendar/templates/calendar.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<div class="container" style="color:#995a07;font-size:1em;font-weight: bold;">
    <div class="row" style="color"><hr/></div>
    <div class="row">
        <div class="col s2 offset-s2"><a href="{% url 'todolist:today_frined' %}">TODAY</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_issue' %}">URL 모음</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_best' %}"><span style="font-color:#995a07;">베스트샷</span></a></div>
        <div class="col s2"><a href="{% url 'todolist:today_workout_list' %}">일기쓰기</a></div>
        <div class="col s2"><a style = "font-size: 18px" href="{% url 'calendar:workout_calendar' %}">이전기록</a></div>
    </div>
    <div class="row"><hr/></div>
</div>


<main>

<div class="container">
<!-- To invalidate browser cache-->
<link rel="stylesheet" type="text/css" href="{{ STATIC_PREFIX }}css/calendar.css?ver=2"/>

<div class="calendar">
    {{ calendar }}
</div>
{% endblock %}

workoutscheduler_project-master/workoutcalendar/templates/child.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<div class="container" style="color:#995a07;font-size:1em;font-weight: bold;">
    <div class="row" style="color"><hr/></div>
    <div class="row">
        <div class="col s2 offset-s2"><a href="{% url 'todolist:today_frined' %}">TODAY</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_issue' %}">URL 모음</a></div>
        <div class="col s2"><a href="{% url 'todolist:today_best' %}"><span style="font-color:#995a07;">베스트샷</span></a></div>
        <div class="col s2"><a href="{% url 'todolist:today_workout_list' %}">일기쓰기</a></div>
        <div class="col s2"><a style = "font-size: 18px" href="{% url 'calendar:workout_calendar' %}">이전기록</a></div>
    </div>
    <div class="row"><hr/></div>
</div>


<main>

<div class="container">
<div>
    <h4 class="grey-text center">{{ day|date:"Y년 N j일, D"}}</h4>


    <div class="row">
        <div class="col l8 offset-l2 s12">
            <div style="background-image: url('/static/img/note.png'); padding-left: 120px;padding-top: 110px;">
                <textarea readonly name="content" cols="50" style="font-size:30pt;height:20em;width:560px;border: none" >{{workout.content}}</textarea>
            </div>
        </div>
    </div>


</div>
{% endblock %}